---
title: "The World Gets Better Every Year"
author: "Debi Gonzalez"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gapminder)
library(gganimate)
library(tidyverse)

# Note that gapminder has data of its own that can be used.
```

```{r make_plot, cache = TRUE, echo = FALSE}

# Life Expectancy and GDP per capita changes over time all over the world.

gapminder %>%

  # filter(year == 1952) %>%
    # Can provide a singular year view od whatever countries/continents we choose to display.
  # filter(country %in% c("Rwanda", "Canada", "China")) %>% 
    # test to see how a country's trajectory looks.
  
  mutate(continent = fct_collapse(continent, Asia = c("Asia", "Oceania"))) %>%
  ggplot(aes(x=gdpPercap, y= lifeExp, size = pop, color = country)) + 
  geom_point(alpha = 0.5, show.legend = FALSE) + 
  scale_color_manual(values = country_colors) +
  
  # scale_color_manual() allows us to manually control the colors.
  # country_colors comes from the gapminder package that assigns a numerical
  # color cue that gives a different shade to each country within a continent.
  
  facet_grid(~continent) +
  
  # GDP is lognormaly distributed (has fat tail) so we need to use a log axis to
  # "stretch out"" the data.
  
  scale_x_log10( breaks = c(1000, 10000), labels = c("$1,000", "$10,000")) +
  labs(title = "The World Gets Better Every Year: {frame_time}", caption = "Source: gapminder package") +
  xlab("GDP Per Capita") + 
  ylab("Life Expectancy") +
  
  # Now that we have a good looking plot, we add a few key lines of animation,
  # for which sometimes it is necessary to install packages gifski and png for
  # it to work.
  
  transition_time(year) 
    
```

